FROM ubuntu:22.04

# Node 설치
RUN apt-get update && apt-get install -y curl \
  && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
  && apt-get install -y nodejs \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# package.json 복사 후 설치
COPY package*.json ./

#############

RUN npm install

# 소스 복사
COPY server.cjs .

EXPOSE 3001
CMD ["node", "server.cjs"]
